version: "3.8"

services:
  frontend:
    build:
      context: ./lunch-order-app-frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://localhost:8000

  backend:
    build:
      context: ./lunch-order-app-backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/lunchapp
    volumes:
      - ./lunch-order-app-backend/prisma:/app/prisma
    command: >
      sh -c "
      npx prisma generate &&
      npx prisma migrate dev --name init &&
      npm run start
      "

  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lunchapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
